---
- hosts: all

  vars_files: vars/main.yml
  tasks:
    
    - name: Update installed dnf packages
      become: true
      yum:
        name: '*'
        state: latest
    
    - name: Install software
      become: true
      yum:
        name:
          - firefox
          - sway
          - waybar
          - fontawesome-fonts
          - dunst
          - neofetch
          - vim
          - alacritty
          - exa
          - zsh
          - grim
          - rofi
          - pavucontrol
          - NetworkManager-tui
          - wl-clipboard
          - obs-studio
          - gdm
          - locate
          - flatpak
          - iperf3
          - lutris
        state: present
    
    - name: Enable gdm
      become: true
      service:
        name: gdm
        enabled: yes
    
    # To be replaced with proper ansible module
    
    - name: Enable graphical target
      become: true
      command: systemctl set-default graphical.target
    
    - name: Add the flathub flatpak repository remote to the user installation
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        method: user

    - name: Install flatpaks
      community.general.flatpak:
        name:  
        - com.github.marktext.marktext
        - com.visualstudio.code
        - com.spotify.Client
        - com.discordapp.Discord
        state: present
        method: user