---
- hosts: all

  vars_files:
    # Used in local testing
    - vars/passwd.yml
    - vars/file_paths.yml

  pre_tasks:
    - name: Load variables.
      include_vars: "{{ item }}"
      with_first_found:
      - "vars/packages/{{ ansible_facts['distribution'] }}_packages.yml"
  
  roles:
  - role: packages
    tags: ['base']
  - role: zsh
    tags: ['base']
  - role: sway
    tags: ['base']
  - role: dotfiles
    tags: ['dotfiles']