---
- hosts: all

  tasks:
    - name: Update installed dnf packages
      become: true
      yum:
        name: '*'
        state: latest
    - name: Install software
      become: true
      yum:
        name:
          - firefox
          - sway
          - waybar
          - fontawesome-fonts
          - dunst
          - neofetch
          - vim
          - alacritty
          - exa
          - zsh
          - grim
          - rofi
          - pavucontrol
          - NetworkManager-tui
          - wl-clipboard
          - gdm
          - locate
        state: present
    - name: Enable gdm
      become: true
      service:
        name: gdm
        enabled: yes
    # To be replaced with proper ansible module
    - name: Enable graphical target
      become: true
      command: systemctl set-default graphical.target

