---
- name: Update installed packages
  become: true
  package:
    name: '*'
    state: latest

- name: Install software
  become: true
  package:
    name: "{{ native_packages }}"
    state: present

- name: Add the flathub flatpak repository remote to the user installation
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user

- name: Install flatpaks
  community.general.flatpak:
    name:  "{{ flatpak_packages }}"
    state: present
    method: user

- name: Install alacritty with cargo on Ubuntu
  community.general.cargo:
    name: alacritty
  when: ansible_facts['distribution'] == 'Ubuntu'