---
- name: Download dotfiles repo
  git: 
    repo: 'https://github.com/wilkovv/dotfiles'
    dest: '~/dotfiles'

- name: Create directories for dotfiles
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop: "{{ dotfile_dirs }}"

- name: Create symlinks
  ansible.builtin.file:
    src: "{{ item[0] }}"
    dest: "{{ item[1] }}"
    state: link
  loop: "{{ dotfile_path }}"