---
- name: Install zsh
  become: true
  package: 
    name: zsh
    state: present

- name: Create zsh config directory
  ansible.builtin.file:
    path: "~/.config/zsh"
    state: directory

- name: Clone powerlevel10k repo
  git: 
    repo: 'https://github.com/romkatv/powerlevel10k'
    dest: '~/.config/zsh/powerlevel10k'
  notify: Setup-p10k-fonts

- name: Flush handlers
  meta: flush_handlers

- name: Clone zsh-autosuggestions repo
  git: 
    repo: 'https://github.com/zsh-users/zsh-autosuggestions'
    dest: '~/.config/zsh/zsh-autosuggestions'

- name: Clone zsh-syntax-highlighting repo
  git: 
    repo: 'https://github.com/zsh-users/zsh-syntax-highlighting'
    dest: '~/.config/zsh/zsh-syntax-highlighting-master'

- name: Set zsh as default shell
  become: true
  ansible.builtin.user:
    shell: '/bin/zsh'
    name: "{{ ansible_user }}"
