---
- name: Ensure fonts folder exists
  ansible.builtin.file:
    path: "~/.local/share/fonts"
    state: directory
  listen: "Setup-p10k-fonts"

- name: Get fonts for powerlevel10k
  ansible.builtin.get_url:
    url: "{{ item }}"
    dest: '~/.local/share/fonts/'
  loop: "{{ p10k_fonts }}"
  listen: "Setup-p10k-fonts"